/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines/index'
import { Route as MailboxesIndexRouteImport } from './routes/mailboxes/index'
import { Route as DomainsIndexRouteImport } from './routes/domains/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CustomFiltersIndexRouteImport } from './routes/custom-filters/index'
import { Route as AliasesIndexRouteImport } from './routes/aliases/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin-users/index'
import { Route as SettingsTlsReportsRouteImport } from './routes/settings/tls-reports'
import { Route as SettingsMtaStsRouteImport } from './routes/settings/mta-sts'
import { Route as SettingsDkimRouteImport } from './routes/settings/dkim'
import { Route as SettingsCertificatesRouteImport } from './routes/settings/certificates'
import { Route as SettingsBansRouteImport } from './routes/settings/bans'
import { Route as QueueIdRouteImport } from './routes/queue/$id'
import { Route as PipelinesNewRouteImport } from './routes/pipelines/new'
import { Route as PipelinesLogsRouteImport } from './routes/pipelines/logs'
import { Route as PipelinesIdRouteImport } from './routes/pipelines/$id'
import { Route as MailboxesNewRouteImport } from './routes/mailboxes/new'
import { Route as MailboxesIdRouteImport } from './routes/mailboxes/$id'
import { Route as DomainsNewRouteImport } from './routes/domains/new'
import { Route as DomainsIdRouteImport } from './routes/domains/$id'
import { Route as CustomFiltersNewRouteImport } from './routes/custom-filters/new'
import { Route as CustomFiltersIdRouteImport } from './routes/custom-filters/$id'
import { Route as AliasesNewRouteImport } from './routes/aliases/new'
import { Route as AliasesIdRouteImport } from './routes/aliases/$id'
import { Route as AdminUsersNewRouteImport } from './routes/admin-users/new'
import { Route as AdminUsersIdRouteImport } from './routes/admin-users/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/pipelines/',
  path: '/pipelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesIndexRoute = MailboxesIndexRouteImport.update({
  id: '/mailboxes/',
  path: '/mailboxes/',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIndexRoute = DomainsIndexRouteImport.update({
  id: '/domains/',
  path: '/domains/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFiltersIndexRoute = CustomFiltersIndexRouteImport.update({
  id: '/custom-filters/',
  path: '/custom-filters/',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasesIndexRoute = AliasesIndexRouteImport.update({
  id: '/aliases/',
  path: '/aliases/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/admin-users/',
  path: '/admin-users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTlsReportsRoute = SettingsTlsReportsRouteImport.update({
  id: '/settings/tls-reports',
  path: '/settings/tls-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsMtaStsRoute = SettingsMtaStsRouteImport.update({
  id: '/settings/mta-sts',
  path: '/settings/mta-sts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDkimRoute = SettingsDkimRouteImport.update({
  id: '/settings/dkim',
  path: '/settings/dkim',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCertificatesRoute = SettingsCertificatesRouteImport.update({
  id: '/settings/certificates',
  path: '/settings/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBansRoute = SettingsBansRouteImport.update({
  id: '/settings/bans',
  path: '/settings/bans',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIdRoute = QueueIdRouteImport.update({
  id: '/queue/$id',
  path: '/queue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesNewRoute = PipelinesNewRouteImport.update({
  id: '/pipelines/new',
  path: '/pipelines/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesLogsRoute = PipelinesLogsRouteImport.update({
  id: '/pipelines/logs',
  path: '/pipelines/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIdRoute = PipelinesIdRouteImport.update({
  id: '/pipelines/$id',
  path: '/pipelines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesNewRoute = MailboxesNewRouteImport.update({
  id: '/mailboxes/new',
  path: '/mailboxes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MailboxesIdRoute = MailboxesIdRouteImport.update({
  id: '/mailboxes/$id',
  path: '/mailboxes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsNewRoute = DomainsNewRouteImport.update({
  id: '/domains/new',
  path: '/domains/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsIdRoute = DomainsIdRouteImport.update({
  id: '/domains/$id',
  path: '/domains/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFiltersNewRoute = CustomFiltersNewRouteImport.update({
  id: '/custom-filters/new',
  path: '/custom-filters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFiltersIdRoute = CustomFiltersIdRouteImport.update({
  id: '/custom-filters/$id',
  path: '/custom-filters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasesNewRoute = AliasesNewRouteImport.update({
  id: '/aliases/new',
  path: '/aliases/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AliasesIdRoute = AliasesIdRouteImport.update({
  id: '/aliases/$id',
  path: '/aliases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/admin-users/new',
  path: '/admin-users/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/admin-users/$id',
  path: '/admin-users/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-users/$id': typeof AdminUsersIdRoute
  '/admin-users/new': typeof AdminUsersNewRoute
  '/aliases/$id': typeof AliasesIdRoute
  '/aliases/new': typeof AliasesNewRoute
  '/custom-filters/$id': typeof CustomFiltersIdRoute
  '/custom-filters/new': typeof CustomFiltersNewRoute
  '/domains/$id': typeof DomainsIdRoute
  '/domains/new': typeof DomainsNewRoute
  '/mailboxes/$id': typeof MailboxesIdRoute
  '/mailboxes/new': typeof MailboxesNewRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/logs': typeof PipelinesLogsRoute
  '/pipelines/new': typeof PipelinesNewRoute
  '/queue/$id': typeof QueueIdRoute
  '/settings/bans': typeof SettingsBansRoute
  '/settings/certificates': typeof SettingsCertificatesRoute
  '/settings/dkim': typeof SettingsDkimRoute
  '/settings/mta-sts': typeof SettingsMtaStsRoute
  '/settings/tls-reports': typeof SettingsTlsReportsRoute
  '/admin-users/': typeof AdminUsersIndexRoute
  '/aliases/': typeof AliasesIndexRoute
  '/custom-filters/': typeof CustomFiltersIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/mailboxes/': typeof MailboxesIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-users/$id': typeof AdminUsersIdRoute
  '/admin-users/new': typeof AdminUsersNewRoute
  '/aliases/$id': typeof AliasesIdRoute
  '/aliases/new': typeof AliasesNewRoute
  '/custom-filters/$id': typeof CustomFiltersIdRoute
  '/custom-filters/new': typeof CustomFiltersNewRoute
  '/domains/$id': typeof DomainsIdRoute
  '/domains/new': typeof DomainsNewRoute
  '/mailboxes/$id': typeof MailboxesIdRoute
  '/mailboxes/new': typeof MailboxesNewRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/logs': typeof PipelinesLogsRoute
  '/pipelines/new': typeof PipelinesNewRoute
  '/queue/$id': typeof QueueIdRoute
  '/settings/bans': typeof SettingsBansRoute
  '/settings/certificates': typeof SettingsCertificatesRoute
  '/settings/dkim': typeof SettingsDkimRoute
  '/settings/mta-sts': typeof SettingsMtaStsRoute
  '/settings/tls-reports': typeof SettingsTlsReportsRoute
  '/admin-users': typeof AdminUsersIndexRoute
  '/aliases': typeof AliasesIndexRoute
  '/custom-filters': typeof CustomFiltersIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/domains': typeof DomainsIndexRoute
  '/mailboxes': typeof MailboxesIndexRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/queue': typeof QueueIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-users/$id': typeof AdminUsersIdRoute
  '/admin-users/new': typeof AdminUsersNewRoute
  '/aliases/$id': typeof AliasesIdRoute
  '/aliases/new': typeof AliasesNewRoute
  '/custom-filters/$id': typeof CustomFiltersIdRoute
  '/custom-filters/new': typeof CustomFiltersNewRoute
  '/domains/$id': typeof DomainsIdRoute
  '/domains/new': typeof DomainsNewRoute
  '/mailboxes/$id': typeof MailboxesIdRoute
  '/mailboxes/new': typeof MailboxesNewRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/logs': typeof PipelinesLogsRoute
  '/pipelines/new': typeof PipelinesNewRoute
  '/queue/$id': typeof QueueIdRoute
  '/settings/bans': typeof SettingsBansRoute
  '/settings/certificates': typeof SettingsCertificatesRoute
  '/settings/dkim': typeof SettingsDkimRoute
  '/settings/mta-sts': typeof SettingsMtaStsRoute
  '/settings/tls-reports': typeof SettingsTlsReportsRoute
  '/admin-users/': typeof AdminUsersIndexRoute
  '/aliases/': typeof AliasesIndexRoute
  '/custom-filters/': typeof CustomFiltersIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/domains/': typeof DomainsIndexRoute
  '/mailboxes/': typeof MailboxesIndexRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-users/$id'
    | '/admin-users/new'
    | '/aliases/$id'
    | '/aliases/new'
    | '/custom-filters/$id'
    | '/custom-filters/new'
    | '/domains/$id'
    | '/domains/new'
    | '/mailboxes/$id'
    | '/mailboxes/new'
    | '/pipelines/$id'
    | '/pipelines/logs'
    | '/pipelines/new'
    | '/queue/$id'
    | '/settings/bans'
    | '/settings/certificates'
    | '/settings/dkim'
    | '/settings/mta-sts'
    | '/settings/tls-reports'
    | '/admin-users/'
    | '/aliases/'
    | '/custom-filters/'
    | '/dashboard/'
    | '/domains/'
    | '/mailboxes/'
    | '/pipelines/'
    | '/queue/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-users/$id'
    | '/admin-users/new'
    | '/aliases/$id'
    | '/aliases/new'
    | '/custom-filters/$id'
    | '/custom-filters/new'
    | '/domains/$id'
    | '/domains/new'
    | '/mailboxes/$id'
    | '/mailboxes/new'
    | '/pipelines/$id'
    | '/pipelines/logs'
    | '/pipelines/new'
    | '/queue/$id'
    | '/settings/bans'
    | '/settings/certificates'
    | '/settings/dkim'
    | '/settings/mta-sts'
    | '/settings/tls-reports'
    | '/admin-users'
    | '/aliases'
    | '/custom-filters'
    | '/dashboard'
    | '/domains'
    | '/mailboxes'
    | '/pipelines'
    | '/queue'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin-users/$id'
    | '/admin-users/new'
    | '/aliases/$id'
    | '/aliases/new'
    | '/custom-filters/$id'
    | '/custom-filters/new'
    | '/domains/$id'
    | '/domains/new'
    | '/mailboxes/$id'
    | '/mailboxes/new'
    | '/pipelines/$id'
    | '/pipelines/logs'
    | '/pipelines/new'
    | '/queue/$id'
    | '/settings/bans'
    | '/settings/certificates'
    | '/settings/dkim'
    | '/settings/mta-sts'
    | '/settings/tls-reports'
    | '/admin-users/'
    | '/aliases/'
    | '/custom-filters/'
    | '/dashboard/'
    | '/domains/'
    | '/mailboxes/'
    | '/pipelines/'
    | '/queue/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AliasesIdRoute: typeof AliasesIdRoute
  AliasesNewRoute: typeof AliasesNewRoute
  CustomFiltersIdRoute: typeof CustomFiltersIdRoute
  CustomFiltersNewRoute: typeof CustomFiltersNewRoute
  DomainsIdRoute: typeof DomainsIdRoute
  DomainsNewRoute: typeof DomainsNewRoute
  MailboxesIdRoute: typeof MailboxesIdRoute
  MailboxesNewRoute: typeof MailboxesNewRoute
  PipelinesIdRoute: typeof PipelinesIdRoute
  PipelinesLogsRoute: typeof PipelinesLogsRoute
  PipelinesNewRoute: typeof PipelinesNewRoute
  QueueIdRoute: typeof QueueIdRoute
  SettingsBansRoute: typeof SettingsBansRoute
  SettingsCertificatesRoute: typeof SettingsCertificatesRoute
  SettingsDkimRoute: typeof SettingsDkimRoute
  SettingsMtaStsRoute: typeof SettingsMtaStsRoute
  SettingsTlsReportsRoute: typeof SettingsTlsReportsRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AliasesIndexRoute: typeof AliasesIndexRoute
  CustomFiltersIndexRoute: typeof CustomFiltersIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DomainsIndexRoute: typeof DomainsIndexRoute
  MailboxesIndexRoute: typeof MailboxesIndexRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/pipelines'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/': {
      id: '/mailboxes/'
      path: '/mailboxes'
      fullPath: '/mailboxes/'
      preLoaderRoute: typeof MailboxesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/': {
      id: '/domains/'
      path: '/domains'
      fullPath: '/domains/'
      preLoaderRoute: typeof DomainsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-filters/': {
      id: '/custom-filters/'
      path: '/custom-filters'
      fullPath: '/custom-filters/'
      preLoaderRoute: typeof CustomFiltersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliases/': {
      id: '/aliases/'
      path: '/aliases'
      fullPath: '/aliases/'
      preLoaderRoute: typeof AliasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users/': {
      id: '/admin-users/'
      path: '/admin-users'
      fullPath: '/admin-users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/tls-reports': {
      id: '/settings/tls-reports'
      path: '/settings/tls-reports'
      fullPath: '/settings/tls-reports'
      preLoaderRoute: typeof SettingsTlsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/mta-sts': {
      id: '/settings/mta-sts'
      path: '/settings/mta-sts'
      fullPath: '/settings/mta-sts'
      preLoaderRoute: typeof SettingsMtaStsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dkim': {
      id: '/settings/dkim'
      path: '/settings/dkim'
      fullPath: '/settings/dkim'
      preLoaderRoute: typeof SettingsDkimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/certificates': {
      id: '/settings/certificates'
      path: '/settings/certificates'
      fullPath: '/settings/certificates'
      preLoaderRoute: typeof SettingsCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/bans': {
      id: '/settings/bans'
      path: '/settings/bans'
      fullPath: '/settings/bans'
      preLoaderRoute: typeof SettingsBansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/$id': {
      id: '/queue/$id'
      path: '/queue/$id'
      fullPath: '/queue/$id'
      preLoaderRoute: typeof QueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/new': {
      id: '/pipelines/new'
      path: '/pipelines/new'
      fullPath: '/pipelines/new'
      preLoaderRoute: typeof PipelinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/logs': {
      id: '/pipelines/logs'
      path: '/pipelines/logs'
      fullPath: '/pipelines/logs'
      preLoaderRoute: typeof PipelinesLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/$id': {
      id: '/pipelines/$id'
      path: '/pipelines/$id'
      fullPath: '/pipelines/$id'
      preLoaderRoute: typeof PipelinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/new': {
      id: '/mailboxes/new'
      path: '/mailboxes/new'
      fullPath: '/mailboxes/new'
      preLoaderRoute: typeof MailboxesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mailboxes/$id': {
      id: '/mailboxes/$id'
      path: '/mailboxes/$id'
      fullPath: '/mailboxes/$id'
      preLoaderRoute: typeof MailboxesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/new': {
      id: '/domains/new'
      path: '/domains/new'
      fullPath: '/domains/new'
      preLoaderRoute: typeof DomainsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains/$id': {
      id: '/domains/$id'
      path: '/domains/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof DomainsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-filters/new': {
      id: '/custom-filters/new'
      path: '/custom-filters/new'
      fullPath: '/custom-filters/new'
      preLoaderRoute: typeof CustomFiltersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-filters/$id': {
      id: '/custom-filters/$id'
      path: '/custom-filters/$id'
      fullPath: '/custom-filters/$id'
      preLoaderRoute: typeof CustomFiltersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliases/new': {
      id: '/aliases/new'
      path: '/aliases/new'
      fullPath: '/aliases/new'
      preLoaderRoute: typeof AliasesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliases/$id': {
      id: '/aliases/$id'
      path: '/aliases/$id'
      fullPath: '/aliases/$id'
      preLoaderRoute: typeof AliasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users/new': {
      id: '/admin-users/new'
      path: '/admin-users/new'
      fullPath: '/admin-users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users/$id': {
      id: '/admin-users/$id'
      path: '/admin-users/$id'
      fullPath: '/admin-users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AliasesIdRoute: AliasesIdRoute,
  AliasesNewRoute: AliasesNewRoute,
  CustomFiltersIdRoute: CustomFiltersIdRoute,
  CustomFiltersNewRoute: CustomFiltersNewRoute,
  DomainsIdRoute: DomainsIdRoute,
  DomainsNewRoute: DomainsNewRoute,
  MailboxesIdRoute: MailboxesIdRoute,
  MailboxesNewRoute: MailboxesNewRoute,
  PipelinesIdRoute: PipelinesIdRoute,
  PipelinesLogsRoute: PipelinesLogsRoute,
  PipelinesNewRoute: PipelinesNewRoute,
  QueueIdRoute: QueueIdRoute,
  SettingsBansRoute: SettingsBansRoute,
  SettingsCertificatesRoute: SettingsCertificatesRoute,
  SettingsDkimRoute: SettingsDkimRoute,
  SettingsMtaStsRoute: SettingsMtaStsRoute,
  SettingsTlsReportsRoute: SettingsTlsReportsRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AliasesIndexRoute: AliasesIndexRoute,
  CustomFiltersIndexRoute: CustomFiltersIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DomainsIndexRoute: DomainsIndexRoute,
  MailboxesIndexRoute: MailboxesIndexRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
