services:
  webmail:
    build:
      context: .
      target: dev
    labels:
      - docker-proxy.webmail.host=restmail.localhost
      - docker-proxy.webmail.port=3000
      - docker-proxy.webmail.path=/webmail
      - docker-proxy.webmail.websocket=true
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_BASE_PATH: /webmail
      VITE_API_URL: http://restmail.localhost/api/v1
