apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "restmail.componentName" (list . "api") }}
  labels:
    {{- include "restmail.componentLabels" (list . "api") | nindent 4 }}
data:
  API_PORT: {{ .Values.api.port | quote }}
  ENVIRONMENT: {{ .Values.api.environment | quote }}
  LOG_LEVEL: {{ .Values.api.logLevel | quote }}
