apiVersion: v1
kind: Service
metadata:
  name: {{ include "restmail.componentName" (list . "imap-gateway") }}
  labels:
    {{- include "restmail.componentLabels" (list . "imap-gateway") | nindent 4 }}
  {{- with .Values.imapGateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.imapGateway.service.type }}
  {{- if and (eq .Values.imapGateway.service.type "LoadBalancer") .Values.imapGateway.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.imapGateway.service.externalTrafficPolicy }}
  {{- end }}
  {{- with .Values.imapGateway.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  selector:
    {{- include "restmail.componentSelectorLabels" (list . "imap-gateway") | nindent 4 }}
  ports:
    - name: imap
      port: {{ .Values.imapGateway.ports.plain }}
      targetPort: imap
      protocol: TCP
    - name: imaps
      port: {{ .Values.imapGateway.ports.tls }}
      targetPort: imaps
      protocol: TCP
