services:
  prometheus:
    image: prom/prometheus:v2.51.0
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./alerting-rules.yml:/etc/prometheus/alerting-rules.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
    dns:
      - 10.99.0.3
    networks:
      mailnet:
        ipv4_address: 10.99.0.30

  grafana:
    image: grafana/grafana:10.4.1
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: restmail
      GF_USERS_ALLOW_SIGN_UP: "false"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - grafana-data:/var/lib/grafana
    networks:
      mailnet:
        ipv4_address: 10.99.0.31

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://restmail:restmail@postgres-mail3:5432/restmail?sslmode=disable"
    networks:
      mailnet:
        ipv4_address: 10.99.0.32

volumes:
  prometheus-data:
  grafana-data:

networks:
  mailnet:
    external: true
    name: ${COMPOSE_PROJECT_NAME:-rest-mail}_mailnet
