services:
  admin:
    build:
      context: .
      target: dev
    labels:
      - docker-proxy.admin.host=restmail.localhost
      - docker-proxy.admin.port=3000
      - docker-proxy.admin.path=/admin
      - docker-proxy.admin.websocket=true
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      VITE_BASE_PATH: /admin
      VITE_API_URL: http://restmail.localhost/api/v1
