services:
  admin:
    build:
      context: .
      target: prod
      args:
        NGINX_BASE_PATH: /admin
    restart: unless-stopped
    environment:
      NGINX_BASE_PATH: /admin
      VITE_API_URL: http://restmail.localhost/api
    labels:
      - docker-proxy.admin.host=restmail.localhost
      - docker-proxy.admin.port=80
      - docker-proxy.admin.path=/admin
    networks:
      mailnet:
        ipv4_address: 172.20.0.27

networks:
  mailnet:
    external: true
    name: ${COMPOSE_PROJECT_NAME:-rest-mail}_mailnet
