package instance

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

// scaffoldComponents is the ordered component set a new rest-mail instance
// gets. IPs are allocated in this order within the instance's block.
var scaffoldComponents = []string{
	"postgres", "api", "smtp-gateway", "imap-gateway",
	"pop3-gateway", "js-filter", "webmail", "admin",
}

const (
	// ipSubnet is the mailnet /24. Instances are allocated within it.
	ipSubnet = "10.99.0."
	// allocStart is the first octet scaffold will hand out. Octets below it
	// are reserved for hand-assigned infrastructure (testbed dnsmasq, the
	// reference servers, monitoring) and the mail3.test fixture.
	allocStart = 50
	// allocEnd is the last usable octet.
	allocEnd = 250
)

// ScaffoldResult is everything `instance scaffold` produces for a new instance.
type ScaffoldResult struct {
	Domain   string
	Slug     string
	Profile  string            // substrate profile used ("testbed" | "host")
	Manifest []byte            // manifest.yml
	Secrets  []byte            // secrets.env (gitignored)
	Config   []byte            // config.env (rendered from Manifest)
	IPs      map[string]string // component -> IP, for the summary banner (empty in the host profile)
}

// scaffoldProfile is a named substrate flavor: which manifest template to emit
// and whether scaffold allocates mailnet IPs. Profiles ONLY change scaffold
// DEFAULTS — render/check and the env contract are identical for both.
type scaffoldProfile struct {
	name        string
	template    string
	allocateIPs bool // testbed: allocate a 10.99.0.x block; host: leave IPs unset
}

// lookupProfile resolves the --profile value to its definition. The empty
// string and "testbed" both select the testbed profile (today's behavior);
// "host" selects the real-host profile. Any other value is an error.
func lookupProfile(name string) (scaffoldProfile, error) {
	switch name {
	case "", "testbed":
		return scaffoldProfile{name: "testbed", template: scaffoldTemplate, allocateIPs: true}, nil
	case "host":
		return scaffoldProfile{name: "host", template: scaffoldHostTemplate, allocateIPs: false}, nil
	default:
		return scaffoldProfile{}, fmt.Errorf("unknown profile %q (want testbed|host)", name)
	}
}

// Scaffold builds a new instance definition for domain using the named substrate
// profile ("testbed" | "host"; empty → testbed). The testbed profile allocates a
// free mailnet IP block by scanning the manifests already under instancesDir; the
// host profile leaves component IPs unset for the deployer to assign. It does not
// write anything or bring anything up.
func Scaffold(domain, instancesDir, profile string) (*ScaffoldResult, error) {
	if domain == "" {
		return nil, fmt.Errorf("domain is required")
	}
	prof, err := lookupProfile(profile)
	if err != nil {
		return nil, err
	}
	slug := slugFor(domain)

	ips := make(map[string]string, len(scaffoldComponents))
	if prof.allocateIPs {
		used, err := usedOctets(instancesDir)
		if err != nil {
			return nil, err
		}
		block, err := allocateBlock(used, len(scaffoldComponents))
		if err != nil {
			return nil, err
		}
		for i, name := range scaffoldComponents {
			ips[name] = ipSubnet + strconv.Itoa(block+i)
		}
	} else {
		// Host profile: no mailnet allocation — the deployer assigns addresses on
		// their own network. IPs stay empty (the banner and template omit them).
		for _, name := range scaffoldComponents {
			ips[name] = ""
		}
	}

	dbPass, err := genSecret()
	if err != nil {
		return nil, err
	}
	jwt, err := genSecret()
	if err != nil {
		return nil, err
	}
	master, err := genSecret()
	if err != nil {
		return nil, err
	}

	manifest, err := renderScaffoldManifest(prof.template, domain, slug, ips)
	if err != nil {
		return nil, err
	}
	// Round-trip through the strict parser + renderer: guarantees the
	// generated manifest is valid and its config.env is in sync from birth.
	m, err := Parse(manifest)
	if err != nil {
		return nil, fmt.Errorf("generated manifest is invalid: %w", err)
	}
	config, err := Render(m)
	if err != nil {
		return nil, err
	}

	secrets := fmt.Appendf(nil,
		"# Per-instance secrets for %s — GITIGNORED, never committed.\n"+
			"# Generated by `task instance:scaffold`.\n"+
			"MAIL3_DB_PASS=%s\nMAIL3_JWT_SECRET=%s\nMAIL3_MASTER_KEY=%s\n",
		domain, dbPass, jwt, master)

	return &ScaffoldResult{
		Domain: domain, Slug: slug, Profile: prof.name,
		Manifest: manifest, Secrets: secrets, Config: config, IPs: ips,
	}, nil
}

// slugFor derives a stable container-name token from a domain: the first
// label, lowercased, non-alphanumerics collapsed to nothing. acme.example ->
// "acme", mail4.test -> "mail4".
func slugFor(domain string) string {
	label := domain
	if i := strings.IndexByte(domain, '.'); i >= 0 {
		label = domain[:i]
	}
	var b strings.Builder
	for _, r := range strings.ToLower(label) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// usedOctets scans every instances/*/manifest.yml and returns the set of last
// octets already assigned to a component IP in the mailnet subnet.
func usedOctets(instancesDir string) (map[int]bool, error) {
	used := map[int]bool{}
	entries, err := os.ReadDir(instancesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return used, nil
		}
		return nil, err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		path := filepath.Join(instancesDir, e.Name(), "manifest.yml")
		raw, err := os.ReadFile(path)
		if err != nil {
			continue // not every subdir is an instance
		}
		m, err := Parse(raw)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		for _, c := range m.Components {
			if o, ok := octetOf(c.IP); ok {
				used[o] = true
			}
		}
	}
	return used, nil
}

// octetOf returns the last octet of an IP in the mailnet subnet.
func octetOf(ip string) (int, bool) {
	if !strings.HasPrefix(ip, ipSubnet) {
		return 0, false
	}
	o, err := strconv.Atoi(strings.TrimPrefix(ip, ipSubnet))
	if err != nil {
		return 0, false
	}
	return o, true
}

// allocateBlock returns the first octet of the lowest free contiguous block of
// the given size at or above allocStart.
func allocateBlock(used map[int]bool, size int) (int, error) {
	for start := allocStart; start+size-1 <= allocEnd; start++ {
		free := true
		for o := start; o < start+size; o++ {
			if used[o] {
				free = false
				break
			}
		}
		if free {
			return start, nil
		}
	}
	return 0, fmt.Errorf("no free /%d-host block in %s%d-%d", size, ipSubnet, allocStart, allocEnd)
}

// genSecret returns 32 cryptographically-random bytes, hex-encoded.
func genSecret() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func renderScaffoldManifest(tmpl, domain, slug string, ips map[string]string) ([]byte, error) {
	t, err := template.New("manifest").Parse(tmpl)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	err = t.Execute(&b, map[string]any{"Domain": domain, "Slug": slug, "IP": ips})
	return b.Bytes(), err
}

// scaffoldTemplate mirrors the mail3.test fixture manifest, parameterized.
// Project + proxy_host are per-instance so container names and proxy vhosts
// don't collide. Ports keep the standard defaults (edit them if you need two
// instances publishing to the host at once).
const scaffoldTemplate = `# Logical mail instance: {{.Domain}} (generated by ` + "`task instance:scaffold`" + `).
# Edit freely, then re-run ` + "`task instance:render INSTANCE={{.Domain}}`" + `.

# ── envelope: logical, implementation-agnostic ──────────────────────────
domain:     {{.Domain}}
hostname:   {{.Domain}}
proxy_host: {{.Slug}}.localhost

# ── substrate placement (testbed) ───────────────────────────────────────
project:        rest-mail-{{.Slug}}
network:        testbed_mailnet
certs_volume:   testbed_certs
testbed_dns_ip: 10.99.0.10
dns_provider:   testbed-dnsmasq
cert_provider:  testbed-certgen

# ── image source ────────────────────────────────────────────────────────
registry:  ghcr.io/rest-mail
image_tag: dev

# ── runtime ─────────────────────────────────────────────────────────────
log_level:    debug
environment:  development
mailnet_only: true    # secondary instance — reachable on the mailnet only, no
                      # host-port publishing, so it can run beside the primary
internal_mtls: true   # secure-by-default for NEW instances: gateways authenticate
                      # to the API over mutual TLS. ` + "`task instance:new`" + ` provisions
                      # the certs (instance:mtls:issue) automatically. A bare binary
                      # stays off (compiled-in INTERNAL_MTLS_ENABLED=false), so
                      # non-provisioned/upgraded deployments are unaffected.

db:
  name: restmail
  user: restmail

# ── additional served domains (optional) ────────────────────────────────
# This instance serves the primary ` + "`domain`" + ` above. To serve MORE domains from
# the same stack, declare them here — each gets its own DB row, DKIM
# selector/key, and DNS records provisioned at instance-up (` + "`task instance:new`" + `).
# The primary is NOT repeated here. Uncomment and edit:
#
# domains:
#   - name: example.test
#     server_type: restmail      # or: traditional
#     dkim: { selector: default, bits: 2048 }

# ── public TLS (optional) ───────────────────────────────────────────────
# The serving cert is issued by ` + "`task instance:certs:issue`" + ` per ` + "`cert_provider`" + ` above.
# It automatically covers every served domain's mail hostname; add MORE SANs
# (autoconfig, mta-sts, a vanity host) with extra_hostnames. cert_provider:
#   testbed-certgen  (default) issue via the testbed reference-certgen
#   manual                     drop <hostname>.{crt,key} into the certs volume yourself
#   letsencrypt / acme         declare acme: below (ACME client not yet implemented)
# Uncomment and edit:
#
# tls:
#   extra_hostnames: [autoconfig.{{.Domain}}, mta-sts.{{.Domain}}]
#   acme:
#     enabled: true
#     email:   hostmaster@{{.Domain}}
#     staging: true              # flip to false for production issuance

# ── binding: components on the substrate (IPs allocated at scaffold time) ─
components:
  - { name: postgres, ip: {{index .IP "postgres"}} }
  - name: api
    ip: {{index .IP "api"}}
    port: 8080
  - name: smtp-gateway
    ip: {{index .IP "smtp-gateway"}}
    ports: { inbound: 25, submission: 587, submission_tls: 465 }
  - name: imap-gateway
    ip: {{index .IP "imap-gateway"}}
    ports: { plain: 143, tls: 993 }
  - name: pop3-gateway
    ip: {{index .IP "pop3-gateway"}}
    ports: { plain: 110, tls: 995 }
  - { name: js-filter, ip: {{index .IP "js-filter"}} }
  - { name: webmail,   ip: {{index .IP "webmail"}} }
  - { name: admin,     ip: {{index .IP "admin"}} }
`

// scaffoldHostTemplate is the real-host (non-testbed) substrate profile. It is
// the same logical instance as the testbed template with the testbed substrate
// stripped out: NO 10.99.0.x mailnet IPs (the deployer assigns addresses on
// their own network), NO testbed_dns_ip / testbed-dnsmasq / testbed-certgen /
// testbed_* volumes, a BLANK registry to fill in, mailnet_only: false (publish
// on real interfaces), a production runtime posture, and cert_provider: manual
// (drop your own cert into the certs volume — a real host has no reference
// certgen). It renders and passes `instance:check` unchanged; the env contract
// is identical to the testbed profile. internal_mtls stays on (secure-by-default;
// `task instance:new` provisions the internal CA regardless of substrate).
const scaffoldHostTemplate = `# Logical mail instance: {{.Domain}} (generated by ` + "`instance scaffold -profile host`" + `).
# Real-host profile: fill in the substrate placeholders below (registry, network,
# component addresses), drop your serving cert into the certs volume
# (cert_provider: manual), then re-run ` + "`task instance:render INSTANCE={{.Domain}}`" + `.

# ── envelope: logical, implementation-agnostic ──────────────────────────
domain:     {{.Domain}}
hostname:   {{.Domain}}
proxy_host: {{.Slug}}.localhost

# ── substrate placement (real host — NOT the testbed) ───────────────────
# Fill these in for your host: ` + "`network`" + ` is the docker network and
# ` + "`certs_volume`" + ` the volume holding the serving cert/key + internal CA
# (both created on ` + "`task instance:up`" + `). NO testbed dnsmasq/certgen assumptions.
project:       rest-mail-{{.Slug}}
network:       {{.Slug}}_net
certs_volume:  {{.Slug}}_certs
dns_provider:  manual    # you manage DNS at your registrar/provider
cert_provider: manual    # drop <hostname>.{crt,key} into the certs volume;
                         #   switch to acme once the ACME client lands

# ── image source ────────────────────────────────────────────────────────
registry:  ""          # REQUIRED: set to your image registry, e.g. registry.example.com/yourorg
image_tag: dev         # pin to a released tag for production

# ── runtime ─────────────────────────────────────────────────────────────
log_level:    info
environment:  production
mailnet_only: false    # real host — publish gateway/API host ports on real interfaces
internal_mtls: true    # secure-by-default: gateways authenticate to the API over
                       # mutual TLS. ` + "`task instance:new`" + ` provisions the internal CA +
                       # certs (instance:mtls:issue) automatically, on any substrate.

db:
  name: restmail
  user: restmail

# ── additional served domains (optional) ────────────────────────────────
# This instance serves the primary ` + "`domain`" + ` above. To serve MORE domains from
# the same stack, declare them here — each gets its own DB row, DKIM
# selector/key, and DNS records provisioned at instance-up (` + "`task instance:new`" + `).
# The primary is NOT repeated here. Uncomment and edit:
#
# domains:
#   - name: example.com
#     server_type: restmail      # or: traditional
#     dkim: { selector: default, bits: 2048 }

# ── public TLS ──────────────────────────────────────────────────────────
# cert_provider: manual (above) means YOU provide the serving cert: drop
# <hostname>.{crt,key} into the certs volume; ` + "`task instance:certs:issue`" + ` only
# validates it (no issuance). The cert must cover every served domain's mail
# hostname; add MORE SANs (autoconfig, mta-sts, a vanity host) with
# extra_hostnames. Switch cert_provider to acme/letsencrypt and declare acme:
# below once the ACME client lands. Uncomment and edit:
#
# tls:
#   extra_hostnames: [autoconfig.{{.Domain}}, mta-sts.{{.Domain}}]
#   acme:
#     enabled: true
#     email:   hostmaster@{{.Domain}}
#     staging: true              # flip to false for production issuance

# ── binding: components on the substrate ─────────────────────────────────
# Real-host profile leaves component IPs UNSET — assign addresses on your own
# network (or bind to real interfaces) before ` + "`task instance:up`" + `. Ports keep the
# standard mail defaults.
components:
  - { name: postgres }
  - name: api
    port: 8080
  - name: smtp-gateway
    ports: { inbound: 25, submission: 587, submission_tls: 465 }
  - name: imap-gateway
    ports: { plain: 143, tls: 993 }
  - name: pop3-gateway
    ports: { plain: 110, tls: 995 }
  - { name: js-filter }
  - { name: webmail }
  - { name: admin }
`
