package instance

import (
	"bytes"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"text/template"
)

// scaffoldComponents is the ordered component set a new rest-mail instance
// gets. IPs are allocated in this order within the instance's block.
var scaffoldComponents = []string{
	"postgres", "api", "smtp-gateway", "imap-gateway",
	"pop3-gateway", "js-filter", "webmail", "admin",
}

const (
	// ipSubnet is the mailnet /24. Instances are allocated within it.
	ipSubnet = "10.99.0."
	// allocStart is the first octet scaffold will hand out. Octets below it
	// are reserved for hand-assigned infrastructure (testbed dnsmasq, the
	// reference servers, monitoring) and the mail3.test fixture.
	allocStart = 50
	// allocEnd is the last usable octet.
	allocEnd = 250
)

// ScaffoldResult is everything `instance scaffold` produces for a new instance.
type ScaffoldResult struct {
	Domain   string
	Slug     string
	Manifest []byte            // manifest.yml
	Secrets  []byte            // secrets.env (gitignored)
	Config   []byte            // config.env (rendered from Manifest)
	IPs      map[string]string // component -> IP, for the summary banner
}

// Scaffold builds a new instance definition for domain, allocating a free IP
// block by scanning the manifests already under instancesDir. It does not
// write anything or bring anything up.
func Scaffold(domain, instancesDir string) (*ScaffoldResult, error) {
	if domain == "" {
		return nil, fmt.Errorf("domain is required")
	}
	slug := slugFor(domain)

	used, err := usedOctets(instancesDir)
	if err != nil {
		return nil, err
	}
	block, err := allocateBlock(used, len(scaffoldComponents))
	if err != nil {
		return nil, err
	}

	ips := make(map[string]string, len(scaffoldComponents))
	for i, name := range scaffoldComponents {
		ips[name] = ipSubnet + strconv.Itoa(block+i)
	}

	dbPass, err := genSecret()
	if err != nil {
		return nil, err
	}
	jwt, err := genSecret()
	if err != nil {
		return nil, err
	}
	master, err := genSecret()
	if err != nil {
		return nil, err
	}

	manifest, err := renderScaffoldManifest(domain, slug, ips)
	if err != nil {
		return nil, err
	}
	// Round-trip through the strict parser + renderer: guarantees the
	// generated manifest is valid and its config.env is in sync from birth.
	m, err := Parse(manifest)
	if err != nil {
		return nil, fmt.Errorf("generated manifest is invalid: %w", err)
	}
	config, err := Render(m)
	if err != nil {
		return nil, err
	}

	secrets := fmt.Appendf(nil,
		"# Per-instance secrets for %s — GITIGNORED, never committed.\n"+
			"# Generated by `task instance:scaffold`.\n"+
			"MAIL3_DB_PASS=%s\nMAIL3_JWT_SECRET=%s\nMAIL3_MASTER_KEY=%s\n",
		domain, dbPass, jwt, master)

	return &ScaffoldResult{
		Domain: domain, Slug: slug,
		Manifest: manifest, Secrets: secrets, Config: config, IPs: ips,
	}, nil
}

// slugFor derives a stable container-name token from a domain: the first
// label, lowercased, non-alphanumerics collapsed to nothing. acme.example ->
// "acme", mail4.test -> "mail4".
func slugFor(domain string) string {
	label := domain
	if i := strings.IndexByte(domain, '.'); i >= 0 {
		label = domain[:i]
	}
	var b strings.Builder
	for _, r := range strings.ToLower(label) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// usedOctets scans every instances/*/manifest.yml and returns the set of last
// octets already assigned to a component IP in the mailnet subnet.
func usedOctets(instancesDir string) (map[int]bool, error) {
	used := map[int]bool{}
	entries, err := os.ReadDir(instancesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return used, nil
		}
		return nil, err
	}
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		path := filepath.Join(instancesDir, e.Name(), "manifest.yml")
		raw, err := os.ReadFile(path)
		if err != nil {
			continue // not every subdir is an instance
		}
		m, err := Parse(raw)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", path, err)
		}
		for _, c := range m.Components {
			if o, ok := octetOf(c.IP); ok {
				used[o] = true
			}
		}
	}
	return used, nil
}

// octetOf returns the last octet of an IP in the mailnet subnet.
func octetOf(ip string) (int, bool) {
	if !strings.HasPrefix(ip, ipSubnet) {
		return 0, false
	}
	o, err := strconv.Atoi(strings.TrimPrefix(ip, ipSubnet))
	if err != nil {
		return 0, false
	}
	return o, true
}

// allocateBlock returns the first octet of the lowest free contiguous block of
// the given size at or above allocStart.
func allocateBlock(used map[int]bool, size int) (int, error) {
	for start := allocStart; start+size-1 <= allocEnd; start++ {
		free := true
		for o := start; o < start+size; o++ {
			if used[o] {
				free = false
				break
			}
		}
		if free {
			return start, nil
		}
	}
	return 0, fmt.Errorf("no free /%d-host block in %s%d-%d", size, ipSubnet, allocStart, allocEnd)
}

// genSecret returns 32 cryptographically-random bytes, hex-encoded.
func genSecret() (string, error) {
	buf := make([]byte, 32)
	if _, err := rand.Read(buf); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf), nil
}

func renderScaffoldManifest(domain, slug string, ips map[string]string) ([]byte, error) {
	t, err := template.New("manifest").Parse(scaffoldTemplate)
	if err != nil {
		return nil, err
	}
	var b bytes.Buffer
	err = t.Execute(&b, map[string]any{"Domain": domain, "Slug": slug, "IP": ips})
	return b.Bytes(), err
}

// scaffoldTemplate mirrors the mail3.test fixture manifest, parameterized.
// Project + proxy_host are per-instance so container names and proxy vhosts
// don't collide. Ports keep the standard defaults (edit them if you need two
// instances publishing to the host at once).
const scaffoldTemplate = `# Logical mail instance: {{.Domain}} (generated by ` + "`task instance:scaffold`" + `).
# Edit freely, then re-run ` + "`task instance:render INSTANCE={{.Domain}}`" + `.

# ── envelope: logical, implementation-agnostic ──────────────────────────
domain:     {{.Domain}}
hostname:   {{.Domain}}
proxy_host: {{.Slug}}.localhost

# ── substrate placement (testbed) ───────────────────────────────────────
project:        rest-mail-{{.Slug}}
network:        testbed_mailnet
certs_volume:   testbed_certs
testbed_dns_ip: 10.99.0.10
dns_provider:   testbed-dnsmasq
cert_provider:  testbed-certgen

# ── image source ────────────────────────────────────────────────────────
registry:  ghcr.io/rest-mail
image_tag: dev

# ── runtime ─────────────────────────────────────────────────────────────
log_level:    debug
environment:  development
mailnet_only: true    # secondary instance — reachable on the mailnet only, no
                      # host-port publishing, so it can run beside the primary
internal_mtls: true   # secure-by-default for NEW instances: gateways authenticate
                      # to the API over mutual TLS. ` + "`task instance:new`" + ` provisions
                      # the certs (instance:mtls:issue) automatically. A bare binary
                      # stays off (compiled-in INTERNAL_MTLS_ENABLED=false), so
                      # non-provisioned/upgraded deployments are unaffected.

db:
  name: restmail
  user: restmail

# ── additional served domains (optional) ────────────────────────────────
# This instance serves the primary ` + "`domain`" + ` above. To serve MORE domains from
# the same stack, declare them here — each gets its own DB row, DKIM
# selector/key, and DNS records provisioned at instance-up (` + "`task instance:new`" + `).
# The primary is NOT repeated here. Uncomment and edit:
#
# domains:
#   - name: example.test
#     server_type: restmail      # or: traditional
#     dkim: { selector: default, bits: 2048 }

# ── binding: components on the substrate (IPs allocated at scaffold time) ─
components:
  - { name: postgres, ip: {{index .IP "postgres"}} }
  - name: api
    ip: {{index .IP "api"}}
    port: 8080
  - name: smtp-gateway
    ip: {{index .IP "smtp-gateway"}}
    ports: { inbound: 25, submission: 587, submission_tls: 465 }
  - name: imap-gateway
    ip: {{index .IP "imap-gateway"}}
    ports: { plain: 143, tls: 993 }
  - name: pop3-gateway
    ip: {{index .IP "pop3-gateway"}}
    ports: { plain: 110, tls: 995 }
  - { name: js-filter, ip: {{index .IP "js-filter"}} }
  - { name: webmail,   ip: {{index .IP "webmail"}} }
  - { name: admin,     ip: {{index .IP "admin"}} }
`
