#!/bin/sh
set -e

# Trust the project CA certificate if present (generated by certgen).
if [ -f /certs/ca.crt ]; then
    cp /certs/ca.crt /usr/local/share/ca-certificates/restmail-ca.crt
    update-ca-certificates 2>/dev/null || true
fi

exec "$@"
