services:
  website:
    image: nginx:alpine
    build:
      context: .
    restart: unless-stopped
    labels:
      - docker-proxy.website.host=restmail.localhost
      - docker-proxy.website.port=80
      - docker-proxy.website.path=/
    ports:
      - "8090:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
      mailnet:
        ipv4_address: 172.20.0.26

networks:
  mailnet:
    external: true
    name: ${COMPOSE_PROJECT_NAME:-rest-mail}_mailnet
